### ISSUE TITLE
Please add support for C++

### ISSUE THREAD

**Issue by clairec03** [AleksaGavric/zencomprint#1]
As titled.

**Comment by AleksaGavric** [comment]
Sure thing, coming later this week! Anything else? Would you like for me to make the comments and prints uneditable once hidden? It would prevent silly mistakes.

**Comment by AleksaGavric** [comment]
Would you want C too?

**Comment by clairec03** [comment]
That'd be great and shouldn't be too difficult given C and C++'s similarity.

**Comment by AleksaGavric** [comment]
Uploading a new extension soon that has greated language support and more features. Will deprecate this one and link the new one
